---
- name: Install and start Jenkins
  hosts: all
  become: yes
  tasks:
    - name: Update the apt package index
      apt:
        update_cache: yes

    - name: Install required packages for adding the Docker repository
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']
        state: present

    - name: Add the GPG key for the Docker repository
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add the Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable

    - name: Update the apt package index again
      apt:
        update_cache: yes

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present

    - name: Pull the Jenkins image from the Docker registry
      shell: "docker pull jenkins/jenkins:lts"

    - name: Run the Jenkins image
      shell: "docker run -p 8080:8080 -p 50000:50000 jenkins/jenkins:lts"
