---
- name: Run "docker-compose up -d web_dev"
  hosts: localhost
  become: true
  tasks:
    - name: Check if the web_dev container is running
      docker_container_info:
        name: web_dev
      register: container_status
    - name: Run "docker-compose up -d web_dev"
      docker_compose:
        project_src: /home/dan/code/cuddly-disco
        state: up
        services:
          - web_dev
      when: container_status.state.Running != true


#In this playbook, the first task uses the shell module to check if the web_dev container is running by using the docker ps command. 
#It filters the output to only show container names that match web_dev and it only returns the name of the container.
#The register option is used to save the output of the command in a variable called `container